default:
  image: docker:25-dind
  services:
    - docker:25-dind

  before_script:
    - BASEDIR=$(pwd)
    - id
    - echo $BASEDIR
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build

variables:
  REGISTRYPATH: "$CI_REGISTRY/onacy/docker/container"

build_php:
  stage: build
  script:
    - |
      DATE=$(date +%Y%m%d%H%M)
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        export TAG="${REGISTRYPATH}/php:php${PHP_VERSION}_node${NODE_VERSION}"
        export TAGDATE="${REGISTRYPATH}/php:php${PHP_VERSION}_node${NODE_VERSION}_${DATE}"
      else
        export TAG="${REGISTRYPATH}/${CI_COMMIT_REF_NAME}/php:php${PHP_VERSION}_node${NODE_VERSION}"
        export TAGDATE="${REGISTRYPATH}/${CI_COMMIT_REF_NAME}/php:php${PHP_VERSION}_node${NODE_VERSION}_${DATE}"
      fi
      cd $BASEDIR/php${PHP_VERSION}
      docker build --pull -t $TAG -t $TAGDATE . \
        --build-arg "NODE_VERSION=${NODE_VERSION}"
      docker push $TAG
      docker push $TAGDATE
  parallel:
    matrix:
      - PHP_VERSION: "8.2"
        NODE_VERSION: "16"
      - PHP_VERSION: "8.3"
        NODE_VERSION: "18"
      - PHP_VERSION: "8.2"
        NODE_VERSION: "18"
      - PHP_VERSION: "8.1"
        NODE_VERSION: "18"
      - PHP_VERSION: "8.3"
        NODE_VERSION: "20"
      - PHP_VERSION: "8.2"
        NODE_VERSION: "20"
      - PHP_VERSION: "8.1"
        NODE_VERSION: "20"

build_caddy_plain:
  stage: build
  script:
    - |
      DATE=$(date +%Y%m%d%H%M)
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        export TAG="${REGISTRYPATH}/caddy_plain:node${NODE_VERSION}"
        export TAGDATE="${REGISTRYPATH}/caddy_plain:node${NODE_VERSION}_${DATE}"
      else
        export TAG="${REGISTRYPATH}/${CI_COMMIT_REF_NAME}/caddy_plain:node${NODE_VERSION}"
        export TAGDATE="${REGISTRYPATH}/${CI_COMMIT_REF_NAME}/caddy_plain:node${NODE_VERSION}_${DATE}"
      fi
      cd $BASEDIR/caddy_plain
      docker build --pull -t $TAG -t $TAGDATE . \
        --build-arg "NODE_VERSION=${NODE_VERSION}"
      docker push $TAG
      docker push $TAGDATE
  parallel:
    matrix:
      - NODE_VERSION: 18
      - NODE_VERSION: 20

build_php_apache_mod_php:
  stage: build
  script:
    - |
      DATE=$(date +%Y%m%d%H%M)
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        export TAG="${REGISTRYPATH}/php-apache-mod-php:php${PHP_VERSION}_node${NODE_VERSION}"
        export TAGDATE="${REGISTRYPATH}/php-apache-mod-php:php${PHP_VERSION}_node${NODE_VERSION}_${DATE}"
      else
        export TAG="${REGISTRYPATH}/${CI_COMMIT_REF_NAME}/php-apache-mod-php:php${PHP_VERSION}_node${NODE_VERSION}"
        export TAGDATE="${REGISTRYPATH}/${CI_COMMIT_REF_NAME}/php-apache-mod-php:php${PHP_VERSION}_node${NODE_VERSION}_${DATE}"
      fi
      cd $BASEDIR/php-apache-mod-php
      docker build --pull -t $TAG -t $TAGDATE . \
        --build-arg "NODE_VERSION=${NODE_VERSION}" \
        --build-arg "PHP_VERSION=${PHP_VERSION}"
      docker push $TAG
      docker push $TAGDATE
  parallel:
    matrix:
      - PHP_VERSION: "8.3"
        NODE_VERSION: "18"
      - PHP_VERSION: "8.2"
        NODE_VERSION: "18"
      - PHP_VERSION: "8.1"
        NODE_VERSION: "18"
      - PHP_VERSION: "8.3"
        NODE_VERSION: "20"
      - PHP_VERSION: "8.2"
        NODE_VERSION: "20"
      - PHP_VERSION: "8.1"
        NODE_VERSION: "20"
