version: "3.9"

name: php_test_${OCY_CI_APP_ENV}

x-cockpit-base: &base
  image: app:${OCY_BUILD_TAG}
  build:
    context: ../php/
    args:
      - APP_ENV=${OCY_CI_APP_ENV}
  networks:
    - backend
  restart: always
  env_file: "./.env"
  volumes:
    - "./app/data/storage/logs:/app/storage/logs"
    - "./app/data/storage/app:/app/storage/app"
    - "./docker-entrypoint.d:/etc/docker-entrypoint.d"

services:

  app:
    <<: *base
    networks:
      - frontend
      - backend
    labels:
      - "traefik.enable=false"
      # this could be the traefik labels

#  db:
#    image: mariadb:10.11
#    restart: always
#    env_file:
#      - ./db/.env
#    networks:
#      - backend
#    volumes:
#      - ./db/data:/var/lib/mysql
#
#  redis:
#    image: "redis:latest"
#    restart: always
#    networks:
#      - backend
#    volumes:
#      - ./redis/data:/data

networks:
  frontend:
    external: true
  backend:
